package Entidades;
// Generated 27-06-2015 20:54:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Administradores generated by hbm2java
 */
public class Administradores  implements java.io.Serializable {


     private String rutAdministrador;
     private String nombres;
     private String apellidos;
     private String especialidad;
     private String estado;
     private String password;
     private String mail;
     private String telefono;
     private Set tickets = new HashSet(0);

    public Administradores() {
    }

	
    public Administradores(String rutAdministrador) {
        this.rutAdministrador = rutAdministrador;
    }
    public Administradores(String rutAdministrador, String nombres, String apellidos, String especialidad, String estado, String password, String mail, String telefono, Set tickets) {
       this.rutAdministrador = rutAdministrador;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.especialidad = especialidad;
       this.estado = estado;
       this.password = password;
       this.mail = mail;
       this.telefono = telefono;
       this.tickets = tickets;
    }
   
    public String getRutAdministrador() {
        return this.rutAdministrador;
    }
    
    public void setRutAdministrador(String rutAdministrador) {
        this.rutAdministrador = rutAdministrador;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }




}


