package Entidades;
// Generated 27-06-2015 20:54:04 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DetalleTicket generated by hbm2java
 */
public class DetalleTicket  implements java.io.Serializable {


     private DetalleTicketId id;
     private Ticket ticket;
     private String descripcion;
     private Date fechaHora;
     private String estado;
     private Set seguimientoDetalles = new HashSet(0);

    public DetalleTicket() {
    }

	
    public DetalleTicket(DetalleTicketId id, Ticket ticket) {
        this.id = id;
        this.ticket = ticket;
    }
    public DetalleTicket(DetalleTicketId id, Ticket ticket, String descripcion, Date fechaHora, String estado, Set seguimientoDetalles) {
       this.id = id;
       this.ticket = ticket;
       this.descripcion = descripcion;
       this.fechaHora = fechaHora;
       this.estado = estado;
       this.seguimientoDetalles = seguimientoDetalles;
    }
   
    public DetalleTicketId getId() {
        return this.id;
    }
    
    public void setId(DetalleTicketId id) {
        this.id = id;
    }
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getSeguimientoDetalles() {
        return this.seguimientoDetalles;
    }
    
    public void setSeguimientoDetalles(Set seguimientoDetalles) {
        this.seguimientoDetalles = seguimientoDetalles;
    }




}


