package Entidades;
// Generated 27-06-2015 20:54:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresas generated by hbm2java
 */
public class Empresas  implements java.io.Serializable {


     private String rutEmpresa;
     private String nombre;
     private String fantasia;
     private String giro;
     private String direccion;
     private String telefono;
     private Set usuarioses = new HashSet(0);

    public Empresas() {
    }

	
    public Empresas(String rutEmpresa) {
        this.rutEmpresa = rutEmpresa;
    }
    public Empresas(String rutEmpresa, String nombre, String fantasia, String giro, String direccion, String telefono, Set usuarioses) {
       this.rutEmpresa = rutEmpresa;
       this.nombre = nombre;
       this.fantasia = fantasia;
       this.giro = giro;
       this.direccion = direccion;
       this.telefono = telefono;
       this.usuarioses = usuarioses;
    }
   
    public String getRutEmpresa() {
        return this.rutEmpresa;
    }
    
    public void setRutEmpresa(String rutEmpresa) {
        this.rutEmpresa = rutEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getFantasia() {
        return this.fantasia;
    }
    
    public void setFantasia(String fantasia) {
        this.fantasia = fantasia;
    }
    public String getGiro() {
        return this.giro;
    }
    
    public void setGiro(String giro) {
        this.giro = giro;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


