package Entidades;
// Generated 27-06-2015 20:54:04 by Hibernate Tools 4.3.1



/**
 * SeguimientoDetalleId generated by hbm2java
 */
public class SeguimientoDetalleId  implements java.io.Serializable {


     private long idSeguimientoDetalle;
     private long detalleTicketIdDetalle;
     private long detalleTicketTicketIdTicket;

    public SeguimientoDetalleId() {
    }

    public SeguimientoDetalleId(long idSeguimientoDetalle, long detalleTicketIdDetalle, long detalleTicketTicketIdTicket) {
       this.idSeguimientoDetalle = idSeguimientoDetalle;
       this.detalleTicketIdDetalle = detalleTicketIdDetalle;
       this.detalleTicketTicketIdTicket = detalleTicketTicketIdTicket;
    }
   
    public long getIdSeguimientoDetalle() {
        return this.idSeguimientoDetalle;
    }
    
    public void setIdSeguimientoDetalle(long idSeguimientoDetalle) {
        this.idSeguimientoDetalle = idSeguimientoDetalle;
    }
    public long getDetalleTicketIdDetalle() {
        return this.detalleTicketIdDetalle;
    }
    
    public void setDetalleTicketIdDetalle(long detalleTicketIdDetalle) {
        this.detalleTicketIdDetalle = detalleTicketIdDetalle;
    }
    public long getDetalleTicketTicketIdTicket() {
        return this.detalleTicketTicketIdTicket;
    }
    
    public void setDetalleTicketTicketIdTicket(long detalleTicketTicketIdTicket) {
        this.detalleTicketTicketIdTicket = detalleTicketTicketIdTicket;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SeguimientoDetalleId) ) return false;
		 SeguimientoDetalleId castOther = ( SeguimientoDetalleId ) other; 
         
		 return (this.getIdSeguimientoDetalle()==castOther.getIdSeguimientoDetalle())
 && (this.getDetalleTicketIdDetalle()==castOther.getDetalleTicketIdDetalle())
 && (this.getDetalleTicketTicketIdTicket()==castOther.getDetalleTicketTicketIdTicket());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdSeguimientoDetalle();
         result = 37 * result + (int) this.getDetalleTicketIdDetalle();
         result = 37 * result + (int) this.getDetalleTicketTicketIdTicket();
         return result;
   }   


}


