package Entidades;
// Generated 26-06-2015 22:31:49 by Hibernate Tools 4.3.1



/**
 * DetalleTicketId generated by hbm2java
 */
public class DetalleTicketId  implements java.io.Serializable {


     private long idDetalle;
     private long ticketIdTicket;

    public DetalleTicketId() {
    }

    public DetalleTicketId(long idDetalle, long ticketIdTicket) {
       this.idDetalle = idDetalle;
       this.ticketIdTicket = ticketIdTicket;
    }
   
    public long getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(long idDetalle) {
        this.idDetalle = idDetalle;
    }
    public long getTicketIdTicket() {
        return this.ticketIdTicket;
    }
    
    public void setTicketIdTicket(long ticketIdTicket) {
        this.ticketIdTicket = ticketIdTicket;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleTicketId) ) return false;
		 DetalleTicketId castOther = ( DetalleTicketId ) other; 
         
		 return (this.getIdDetalle()==castOther.getIdDetalle())
 && (this.getTicketIdTicket()==castOther.getTicketIdTicket());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdDetalle();
         result = 37 * result + (int) this.getTicketIdTicket();
         return result;
   }   


}


