package Entidades;
// Generated 26-06-2015 22:31:49 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SeguimientoDetalle generated by hbm2java
 */
public class SeguimientoDetalle  implements java.io.Serializable {


     private SeguimientoDetalleId id;
     private DetalleTicket detalleTicket;
     private String descripcion;
     private Date fechaHora;
     private String estado;

    public SeguimientoDetalle() {
    }

	
    public SeguimientoDetalle(SeguimientoDetalleId id, DetalleTicket detalleTicket) {
        this.id = id;
        this.detalleTicket = detalleTicket;
    }
    public SeguimientoDetalle(SeguimientoDetalleId id, DetalleTicket detalleTicket, String descripcion, Date fechaHora, String estado) {
       this.id = id;
       this.detalleTicket = detalleTicket;
       this.descripcion = descripcion;
       this.fechaHora = fechaHora;
       this.estado = estado;
    }
   
    public SeguimientoDetalleId getId() {
        return this.id;
    }
    
    public void setId(SeguimientoDetalleId id) {
        this.id = id;
    }
    public DetalleTicket getDetalleTicket() {
        return this.detalleTicket;
    }
    
    public void setDetalleTicket(DetalleTicket detalleTicket) {
        this.detalleTicket = detalleTicket;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


