package Entidades;
// Generated 26-06-2015 22:31:49 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements java.io.Serializable {


     private long idTicket;
     private Administradores administradores;
     private Tecnicos tecnicos;
     private Usuarios usuarios;
     private Date fechaHora;
     private String motivo;
     private String estado;
     private Set detalleTickets = new HashSet(0);

    public Ticket() {
    }

	
    public Ticket(long idTicket, Administradores administradores, Tecnicos tecnicos, Usuarios usuarios) {
        this.idTicket = idTicket;
        this.administradores = administradores;
        this.tecnicos = tecnicos;
        this.usuarios = usuarios;
    }
    public Ticket(long idTicket, Administradores administradores, Tecnicos tecnicos, Usuarios usuarios, Date fechaHora, String motivo, String estado, Set detalleTickets) {
       this.idTicket = idTicket;
       this.administradores = administradores;
       this.tecnicos = tecnicos;
       this.usuarios = usuarios;
       this.fechaHora = fechaHora;
       this.motivo = motivo;
       this.estado = estado;
       this.detalleTickets = detalleTickets;
    }
   
    public long getIdTicket() {
        return this.idTicket;
    }
    
    public void setIdTicket(long idTicket) {
        this.idTicket = idTicket;
    }
    public Administradores getAdministradores() {
        return this.administradores;
    }
    
    public void setAdministradores(Administradores administradores) {
        this.administradores = administradores;
    }
    public Tecnicos getTecnicos() {
        return this.tecnicos;
    }
    
    public void setTecnicos(Tecnicos tecnicos) {
        this.tecnicos = tecnicos;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getDetalleTickets() {
        return this.detalleTickets;
    }
    
    public void setDetalleTickets(Set detalleTickets) {
        this.detalleTickets = detalleTickets;
    }




}


